### PR TITLE
Task 5.2: Results are very tight margin

### PR DESCRIPTION
**Pull request by miri64**
I think that this is copy-pasta, since the other [6Lo task](https://github.com/RIOT-OS/Release-Specs/blob/master/04-single-hop-6lowpan-icmp/04-single-hop-6lowpan-icmp.md) asks for <10% success rate. Additionally, having always a success rate of <1% in a crowded network with 100 1kB packets (which means at least 11 fragments) seems highly unlikely.

### CODE REVIEW

**Comment by smlng** [comment]
in general such thresholds are highly subjective to actual boards used, as well as there distance, time of test and so on. So even 10% could be hard to achieve under certain conditions - that's what I experienced when doing Task 04.05 and 04.06 (interop: remotes <-> samr21-xpro). I would go as far as to say everything below 50% packet loss is a successful test - at least without further insights on what is done. 

I mean 50% still is an arbitrary choice but it also means packets get through. Harder performance metrics only make sense if we could also ensure stable environment/conditions, or not?

**Comment by miri64** [comment]
>  I would go as far as to say everything below 50% packet loss is a successful test

I would say if we have 50% packet loss something is definitely wrong with the driver and should not be cosidered a successful test. For the at86rf2xx we are running fine with 10%, but in the past, especially if the testbed is crowded I had my fair share of problems with this task.

**Comment by miri64** [comment]
(due to the <1% thing)

**Comment by miri64** [comment]
> why you only change task 2 to 10% and not the other two as well then?

Because the other two are native => are wire bound (or not even that) => should be way more reliable.

**Comment by miri64** [comment]
(or to say it with my initial statement: that would be copy-pasta, just the other way around)

**Pull request merged**
