### PR TITLE
Squashed commits of 68

### PR DESCRIPTION
**Pull request by cladmi**
The PR was merged without squashing the commits.
This one reverts all commits and adds squashed versions.

I put the script documentation as commit message.

##### Testing

The current version has the same files as the merge commit in master: `09a90d8`

```
git diff 09a90d8
# says nothing
```

The commit message can be reviewed.

##### Reference PR:

https://github.com/RIOT-OS/Release-Specs/pull/68

### CODE REVIEW

**Comment by jia200x** [comment]
Tested, works as expected. Thank you so much!

**Comment by miri64** [comment]
For future reference: I think it doesn't actually make an accidental merge of un-squashed commits more tidy if you revert and then re-apply squashed. Now the history is even more cluttered.

**Comment by jia200x** [comment]
> For future reference: I think it doesn't actually make an accidental merge of un-squashed commits more tidy if you revert and then re-apply squashed. Now the history is even more cluttered.

Ok. Taken

**Comment by cladmi** [comment]
@miri64 my goal to squash was to at least have somewhere the right commit message introducing it. The first commit description was outdated.
Even if the history is a bit more messy, now doing a `git blame` or a `git log -G` points me first to a valid commit and it is what I tried to ensure by doing these reverts.

**Pull request merged**
