### PR TITLE
11-lorawan: add GNRC LoRaWAN tests

### PR DESCRIPTION
**Pull request by jia200x**
## Contribution Description

This commit adds some GNRC LoRaWAN tests. These tests cover the
different join procedures (OTAA and ABP), sending confirmed and
unconfirmed messages and receiving downlinks from the Network
Server.

## Testing Procedure
Check that the tests make sense

### CODE REVIEW

**Comment by jia200x** [comment]
@aabadie @miri64 @fjmolinas it would be very cool to have this one for the release. The testing procedure is quite "generic" and mostly tries to follow the steps of the first tasks (semtech pkg). So if someone can give it a look I would really appreciate it :)

**Comment by jia200x** [comment]
BTW I have a running RIOTCtrl script that tests this. I will clean it up and see if it makes it by today. In worst case we can merge those tests right after the RC1, but for that we would need to have these specs already in master

**Comment by miri64** [comment]
Ping @aabadie @fjmolinas or @leandrolanzieri? My knowledge of LoRaWAN is too limited to judge the sensibility of those specs.

**Review by leandrolanzieri — APPROVED** [review]
I was running the tests to check that the commands are correct. Everything looks fine.The tests make sense to me: both join procedures are tested, together with confirmed and unconfirmed messages.
ACK!

Note: we can add the test automation that @jia200x is doing on a separate PR, for now it's important to have the specs in for the hard freeze.

**Comment by miri64** [comment]
> Note: we can add the test automation that @jia200x is doing on a separate PR, for now it's important to have the specs in for the hard freeze.

Agreed and actually preferred for me.

PR needs a rebase though before it can get merged.

**Pull request merged**
