### PR TITLE
04-single-hop-6lowpan-icmp: change task08 interval to 350ms

### PR DESCRIPTION
**Pull request by fjmolinas**
This PR does two things:

- homologate examples_test_guide.md and specs
- change payload to work with default 9600 xbee baudrate

I changed the payload since form what I was able to test in 2020.01 and 2019.10 `xbee` can't handle100b payload at 100ms interval.

## Testing procedure

- Run the old spec on 2020.01 and 2019.10
- Run the new spec on 2020.01 and 2019.10

### CODE REVIEW

**Comment by miri64** [comment]
Do we know, why only 50B work? Do we maybe need to change the maximum fragment size for this device in upstream?

**Comment by fjmolinas** [comment]
> Do we know, why only 50B work? Do we maybe need to change the maximum fragment size for this device in upstream?

It has to do with the speed of incoming packets, changing the interval works as well.

**Comment by fjmolinas** [comment]
> It has to do with the speed of incoming packets, changing the interval works as well.

e.g.: 300ms

**Comment by fjmolinas** [comment]
@leandrolanzieri you might want to take a look since managing 2020.04

**Comment by miri64** [comment]
I'd rather would change the speed then. We did the same when the limited packet buffer size created problems with very large packets and asynchronous ping (see https://github.com/RIOT-OS/Release-Specs/pull/123).

**Comment by fjmolinas** [comment]
> I'd rather would change the speed then. We did the same when the limited packet buffer size created problems with very large packets and asynchronous ping (see #123).

Then I'll use the example configuration as the default for both, with that:

```
2020-02-05 12:53:37,762 # 108 bytes from fe80::213:a200:40c2:d4c4: icmp_seq=995 ttl=64 rssi=-61 dBm time=325.717 ms
2020-02-05 12:53:38,112 # 108 bytes from fe80::213:a200:40c2:d4c4: icmp_seq=996 ttl=64 rssi=-62 dBm time=325.740 ms
2020-02-05 12:53:38,462 # 108 bytes from fe80::213:a200:40c2:d4c4: icmp_seq=997 ttl=64 rssi=-61 dBm time=325.767 ms
2020-02-05 12:53:38,812 # 108 bytes from fe80::213:a200:40c2:d4c4: icmp_seq=998 ttl=64 rssi=-61 dBm time=325.822 ms
2020-02-05 12:53:39,162 # 108 bytes from fe80::213:a200:40c2:d4c4: icmp_seq=999 ttl=64 rssi=-62 dBm time=325.832 ms
2020-02-05 12:53:39,829 # 
2020-02-05 12:53:39,833 # --- fe80::213:a200:40c2:d4c4 PING statistics ---
2020-02-05 12:53:39,838 # 1000 packets transmitted, 988 packets received, 1% packet loss
2020-02-05 12:53:39,843 # round-trip min/avg/max = 325.606/325.860/358.934 ms

```

**Comment by miri64** [comment]
Commit and PR title should be adapted then

**Comment by fjmolinas** [comment]
ping @miri64 @leandrolanzieri

**Pull request merged**
