### PR TITLE
09-compile-and-test-one-board: add script to test board

### PR DESCRIPTION
**Pull request by cladmi**
Add a script to compile and execute test on a board and produce file results.

I want to add a new release spec step where board maintainers run tests on their own board, with their normal working setup and give us the compilation/tests results.

I do not call it a "test" as I do not want it blocking for a release, but more as a goal of gathering information on the current state of board support and test suite.

TODO:

* [x] Readme.md
* [x] Make some board maintainers upload their tests results
* [x] Integrate in the release specs (is there any special thing to do ?)
  * Should be ok
  * [x] Allow title with description in the release manager

### Description

This adds a script that goes into all applications and, if the board is supported, calls `make clean all`, and then `make flash test` if there are tests.

It produces results in `results/board/tests/name/` with `compilation.success` or `.failed` and `test.success` or `test.failed`. The goal was to produce file results with the execution trace on failure. I also kept for tests as analyzing the content could also be useful.

The script is wrote to not re-run compilation and tests if the output file exists.
So if you change the tested release, you should update the result-directory or delete only the tests output you want to re-run.

Making it correctly detect if things changed is a problem that should go in the Makefile and be made reliable there. I want this script to be easy to re-run on failed tests.

### Usage

* Have a clean RIOT repository version using a release version
* Plug one board to your computer and check that you can run tests `make -C tests/events all flash test BOARD=your_board`
* Run the script

       ./compile_and_test_for_board.py path_to_riot_directory board_name [optional_results_directory]
* Write a PR with your results to: https://github.com/cladmi/RIOT_2018_07_tests_results

### Uploading results

For this release, I created a repository on my github account where developers can put the results:

https://github.com/cladmi/RIOT_2018_07_tests_results

Where my first tester uploaded their results already.

### Future work

Begin merging parts of the script to the main riot build system to provide it as an integrated features. I just did not have time to write it before the release and using a PR for testing the release is more complex than an external script.

### CODE REVIEW

**Comment by cladmi** [comment]
It can also be used to run tests for [Task #02](https://github.com/RIOT-OS/Release-Specs/blob/master/02-tests/02-tests.md)

**Comment by cladmi** [comment]
> Couldn't this script also be used for Task 02?

That is even why I started using it :) provide tests results for different boards.

The difference from the basic Task 2 is that I also compile everything even if there is no `test` target. I went for this as more "compile time tests" are being added and that getting more compilation outputs could help debug different environments. But that should not be problematic. The specs could also be updated to match this if we really want to.


A thing I may need to adapt if it is for task 2, is that right now, if you re-run it on the same results directory, it does not re-execute compilation and tests for targets that where already successful. Which simplifies a lot handling temporary failures with the hardware and debugging tests issues. But gives "unsafe results" as they may not be up to date but a good enough default for optional tests.

I could change the behavior to by default force re-run, and an option to be `--incremental` instead of being incremental with a `--force` option.

**Comment by cladmi** [comment]
If you want I can move the script to `task 2` and explain here to use the script from there.

**Comment by miri64** [comment]
:+1: to moving the script

**Comment by miri64** [comment]
It's still in 9 though ;-)

**Comment by cladmi** [comment]
I know, I fix some small issues I have when running it.

**Comment by cladmi** [comment]
I squashed the whole history in two commits with one adding the script for task2 and the one adding task 09.

**Comment by cladmi** [comment]
I separated the `flash` task to a specific file output. As it was the problem for one board that it never flashed. Better make it visible.

**Comment by cladmi** [comment]
Note: it will need adapting when https://github.com/RIOT-OS/RIOT/pull/9867 is merged.

It can either wait, or be adapted later.

**Comment by jia200x** [comment]
> Note: it will need adapting when RIOT-OS/RIOT#9867 is merged.
It can either wait, or be adapted later.

It's ok for me to merge and adapt later :)

**Comment by cladmi** [comment]
> It's ok for me to merge and adapt later :)

Ok, just need a ACK and squashing

**Comment by cladmi** [comment]
It will also need to be adapted after https://github.com/RIOT-OS/RIOT/pull/9567 as the `test` detection will change. So maybe wait until both PRs are merged to merge this one.

**Comment by cladmi** [comment]
Updated now that https://github.com/RIOT-OS/RIOT/pull/9567 is merged.

**Comment by jia200x** [comment]
@cladmi are we ready to merge this one?

**Comment by cladmi** [comment]
I think yes, it just needs a positive review and squash.

**Comment by cladmi** [comment]
I noticed I was uploading to another branch name instead of this one… I fixed this.

**Comment by jia200x** [comment]
code style is good (`flake8`) and the script works as described.

**Comment by cladmi** [comment]
It was not squashed :'(

**Comment by jia200x** [comment]
dumb mistake, I owe beers to all maintainers. 
Next steps? :(

**Comment by jia200x** [comment]
sorry :(

**Comment by cladmi** [comment]
I can do a PR that reverts them and add the squashed commit.

**Pull request merged**
