### PR TITLE
Change all spec filenames to README

### PR DESCRIPTION
**Pull request by danpetry**
This makes them more visible in GitHub, so they display immediately when the user enters the test folder.

I'll sort out the merge conflict if/when we think it's a good idea.

### Testing

Discuss and approve if it seems like a good idea.

### CODE REVIEW

**Comment by MrKevinWeiss** [comment]
I think it is a good idea.  @miri64 seems to be included in this.  Any problems?

**Comment by fjmolinas** [comment]
Anything against this @miri64 ?

**Comment by miri64** [comment]
No, mainly needs a rebase.

**Comment by fjmolinas** [comment]
Rebased!

**Comment by fjmolinas** [comment]
Go!

**Comment by miri64** [comment]
Correct me if I'm wrong (especially @bergzand as the next release manager), but the release manager script [should be fine with this](https://github.com/RIOT-OS/RIOT-release-manager/blob/786c727029cdf944bd920fda9cb7c628923afc73/riot_release_manager.py#L192-L206).

**Comment by fjmolinas** [comment]
> Correct me if I'm wrong (especially @bergzand as the next release manager), but the release manager script should also be fine with this.

I think so, ithis is what is pit out of the linked function:

```
[{'name': '01-ci', 'url': 'https://github.com/RIOT-OS/Release-Specs/blob/60a07d852d31f3816e3d8718cb1722e3c892f58d/01-ci/README.md', 'subtasks': [{'name': 'Task #01 - Compile test', 'url': 'https://github.com/RIOT-OS/Release-Specs/blob/60a07d852d31f3816e3d8718cb1722e3c892f58d/01-ci/README.md#task-01---compile-test'}, {'name': 'Task #02 - Unittests on native', 'url': 'https://github.com/RIOT-OS/Release-Specs/blob/60a07d852d31f3816e3d8718cb1722e3c892f58d/01-ci/README.md#task-02---unittests-on-native'}, {'name': 'Task #03 - Unittests on native separated', 'url': 'https://github.com/RIOT-OS/Release-Specs/blob/60a07d852d31f3816e3d8718cb1722e3c892f58d/01-ci/README.md#task-03---unittests-on-native-separated'}, {'name': 'Task #04 - Unittests on iotlab-m3', 'url': 'https://github.com/RIOT-OS/Release-Specs/blob/60a07d852d31f3816e3d8718cb1722e3c892f58d/01-ci/README.md#task-04---unittests-on-iotlab-m3'}]}, {'name': '02-tests', 'url': 'https://github.com/RIOT-OS/Release-Specs/blob/60a07d852d31f3816e3d8718cb1722e3c892f58d/02-tests/README.md', 'subtasks': [{'name': 'Task #01 - All tests on native', 'url': 'https://github.com/RIOT-OS/Release-Specs/blob/60a07d852d31f3816e3d8718cb1722e3c892f58d/02-tests/README.md#task-01---all-tests-on-native'}, {'name': 'Task #02 - Subset of tests on iotlab-m3', 'url': 'https://github.com/RIOT-OS/Release-Specs/blob/60a07d852d31f3816e3d8718cb1722e3c892f58d/02-tests/README.md#task-02---subset-of-tests-on-iotlab-m3'}, {'name': 'Task #03 - Subset of tests on samr21-xpro', 'url': 'https://github.com/RIOT-OS/Release-Specs/blob/60a07d852d31f3816e3d8718cb1722e3c892f58d/02-tests/README.md#task-03---subset-of-tests-on-samr21-xpro'}]}, {'name': '03-single-hop-ipv6-icmp', 'url': 'https://github.com/RIOT-OS/Release-Specs/blob/60a07d852d31f3816e3d8718cb1722e3c892f58d/03-single-hop-ipv6-icmp/README.md', 'subtasks': [{'name': 'Task #01 - ICMPv6 multicast echo on native', 'url': 'https://github.com/RIOT-OS/Release-Specs/blob/60a07d852d31f3816e3d8718cb1722e3c892f58d/03-single-hop-ipv6-icmp/README.md#task-01---icmpv6-multicast-echo-on-native'}, {'name': 'Task #02 - ICMPv6 link-local echo on native', 'url': 'https://github.com/RIOT-OS/Release-Specs/blob/60a07d852d31f3816e3d8718cb1722e3c892f58d/03-single-hop-ipv6-icmp/README.md#task-02---icmpv6-link-local-echo-on-native'}, {'name': 'Task #03 - ICMPv6 link-local echo on native (1 hour)', 'url': 'https://github.com/RIOT-OS/Release-Specs/blob/60a07d852d31f3816e3d8718cb1722e3c892f58d/03-single-hop-ipv6-icmp/README.md#task-03---icmpv6-link-local-echo-on-native-1-hour'}, {'name': 'Task #04 - ICMPv6 stress test on native (1 hour)', 'url': 'https://github.com/RIOT-OS/Release-Specs/blob/60a07d852d31f3816e3d8718cb1722e3c892f58d/03-single-hop-ipv6-icmp/README.md#task-04---icmpv6-stress-test-on-native-1-hour'}, {'name': 'Task #05 - ICMPv6 stress test on native (neighbor cache stress)', 'url': 'https://github.com/RIOT-OS/Release-Specs/blob/60a07d852d31f3816e3d8718cb1722e3c892f58d/03-single-hop-ipv6-icmp/README.md#task-05---icmpv6-stress-test-on-native-neighbor-cache-stress'}, {'name': 'Task #06 - ICMPv6 link-local echo on native (IPv6 fragmentation)', 'url': 'https://github.com/RIOT-OS/Release-Specs/blob/60a07d852d31f3816e3d8718cb1722e3c892f58d/03-single-hop-ipv6-icmp/README.md#task-06---icmpv6-link-local-echo-on-native-ipv6-fragmentation'}]}, {'name': '04-single-hop-6lowpan-icmp', 'url': 'https://github.com/RIOT-OS/Release-Specs/blob/60a07d852d31f3816e3d8718cb1722e3c892f58d/04-single-hop-6lowpan-icmp/example_test_guide.md', 'subtasks': [{'name': 'Task #01 - ICMPv6 link-local echo with iotlab-m3', 'url': 'https://github.com/RIOT-OS/Release-Specs/blob/60a07d852d31f3816e3d8718cb1722e3c892f58d/04-single-hop-6lowpan-icmp/example_test_guide.md#task-01---icmpv6-link-local-echo-with-iotlab-m3'}, {'name': 'Task #02 - ICMPv6 multicast echo with iotlab-m3/samr21-xpro', 'url': 'https://github.com/RIOT-OS/Release-Specs/blob/60a07d852d31f3816e3d8718cb1722e3c892f58d/04-single-hop-6lowpan-icmp/example_test_guide.md#task-02---icmpv6-multicast-echo-with-iotlab-m3samr21-xpro'}, {'name': 'Task #03 - ICMPv6 echo with large payload', 'url': 'https://github.com/RIOT-OS/Release-Specs/blob/60a07d852d31f3816e3d8718cb1722e3c892f58d/04-single-hop-6lowpan-icmp/example_test_guide.md#task-03---icmpv6-echo-with-large-payload'}, {'name': 'Task #04 - ICMPv6 echo with iotlab-m3/samr21-xpro 15 minutes', 'url': 'https://github.com/RIOT-OS/Release-Specs/blob/60a07d852d31f3816e3d8718cb1722e3c892f58d/04-single-hop-6lowpan-icmp/example_test_guide.md#task-04---icmpv6-echo-with-iotlab-m3samr21-xpro-15-minutes'}, {'name': 'Task #05 (Experimental) - ICMPv6 multicast echo with samr21-xpro/remote', 'url': 'https://github.com/RIOT-OS/Release-Specs/blob/60a07d852d31f3816e3d8718cb1722e3c892f58d/04-single-hop-6lowpan-icmp/example_test_guide.md#task-05-experimental---icmpv6-multicast-echo-with-samr21-xproremote'}, {'name': 'Task #06 (Experimental) - ICMPv6 link-local echo with samr21-xpro/remote', 'url': 'https://github.com/RIOT-OS/Release-Specs/blob/60a07d852d31f3816e3d8718cb1722e3c892f58d/04-single-hop-6lowpan-icmp/example_test_guide.md#task-06-experimental---icmpv6-link-local-echo-with-samr21-xproremote'}, {'name': 'Task #07 (Experimental) - ICMPv6 multicast echo with samr21-xpro/zero + xbee', 'url': 'https://github.com/RIOT-OS/Release-Specs/blob/60a07d852d31f3816e3d8718cb1722e3c892f58d/04-single-hop-6lowpan-icmp/example_test_guide.md#task-07-experimental---icmpv6-multicast-echo-with-samr21-xprozero--xbee'}, {'name': 'Task #08 (Experimental) - ICMPv6 echo with samr21-xpro/zero + xbee', 'url': 'https://github.com/RIOT-OS/Release-Specs/blob/60a07d852d31f3816e3d8718cb1722e3c892f58d/04-single-hop-6lowpan-icmp/example_test_guide.md#task-08-experimental---icmpv6-echo-with-samr21-xprozero--xbee'}, {'name': 'Task #09 - ICMPv6 stress test on iotlab-m3', 'url': 'https://github.com/RIOT-OS/Release-Specs/blob/60a07d852d31f3816e3d8718cb1722e3c892f58d/04-single-hop-6lowpan-icmp/example_test_guide.md#task-09---icmpv6-stress-test-on-iotlab-m3'}, {'name': 'Task #10 (Exprimental) - ICMPv6 echo with large payload (IPv6 fragmentation)', 'url': 'https://github.com/RIOT-OS/Release-Specs/blob/60a07d852d31f3816e3d8718cb1722e3c892f58d/04-single-hop-6lowpan-icmp/example_test_guide.md#task-10-exprimental---icmpv6-echo-with-large-payload-ipv6-fragmentation'}]}, {'name': '05-single-hop-route', 'url': 'https://github.com/RIOT-OS/Release-Specs/blob/60a07d852d31f3816e3d8718cb1722e3c892f58d/05-single-hop-route/README.md', 'subtasks': [{'name': 'Task #01 - ICMPv6 echo unicast addresess on native (default route)', 'url': 'https://github.com/RIOT-OS/Release-Specs/blob/60a07d852d31f3816e3d8718cb1722e3c892f58d/05-single-hop-route/README.md#task-01---icmpv6-echo-unicast-addresess-on-native-default-route'}, {'name': 'Task #02 - ICMPv6 echo unicast addresess on iotlab-m3 (default route)', 'url': 'https://github.com/RIOT-OS/Release-Specs/blob/60a07d852d31f3816e3d8718cb1722e3c892f58d/05-single-hop-route/README.md#task-02---icmpv6-echo-unicast-addresess-on-iotlab-m3-default-route'}, {'name': 'Task #03 - ICMPv6 echo unicast addresess on native (specific route)', 'url': 'https://github.com/RIOT-OS/Release-Specs/blob/60a07d852d31f3816e3d8718cb1722e3c892f58d/05-single-hop-route/README.md#task-03---icmpv6-echo-unicast-addresess-on-native-specific-route'}, {'name': 'Task #04 - ICMPv6 echo unicast addresess on iotlab-m3 (static route)', 'url': 'https://github.com/RIOT-OS/Release-Specs/blob/60a07d852d31f3816e3d8718cb1722e3c892f58d/05-single-hop-route/README.md#task-04---icmpv6-echo-unicast-addresess-on-iotlab-m3-static-route'}]}, {'name': '06-single-hop-udp', 'url': 'https://github.com/RIOT-OS/Release-Specs/blob/60a07d852d31f3816e3d8718cb1722e3c892f58d/06-single-hop-udp/README.md', 'subtasks': [{'name': 'Task #01 - UDP on iotlab-m3', 'url': 'https://github.com/RIOT-OS/Release-Specs/blob/60a07d852d31f3816e3d8718cb1722e3c892f58d/06-single-hop-udp/README.md#task-01---udp-on-iotlab-m3'}, {'name': 'Task #02 - UDP on iotlab-m3 (UDP port compression)', 'url': 'https://github.com/RIOT-OS/Release-Specs/blob/60a07d852d31f3816e3d8718cb1722e3c892f58d/06-single-hop-udp/README.md#task-02---udp-on-iotlab-m3-udp-port-compression'}, {'name': 'Task #03 - UDP on native (non-existent neighbor)', 'url': 'https://github.com/RIOT-OS/Release-Specs/blob/60a07d852d31f3816e3d8718cb1722e3c892f58d/06-single-hop-udp/README.md#task-03---udp-on-native-non-existent-neighbor'}, {'name': 'Task #04 - UDP on iotlab-m3 (non-existent neighbor)', 'url': 'https://github.com/RIOT-OS/Release-Specs/blob/60a07d852d31f3816e3d8718cb1722e3c892f58d/06-single-hop-udp/README.md#task-04---udp-on-iotlab-m3-non-existent-neighbor'}, {'name': 'Task #05 - Empty UDP on native', 'url': 'https://github.com/RIOT-OS/Release-Specs/blob/60a07d852d31f3816e3d8718cb1722e3c892f58d/06-single-hop-udp/README.md#task-05---empty-udp-on-native'}, {'name': 'Task #06 - Empty UDP on iotlab-m3', 'url': 'https://github.com/RIOT-OS/Release-Specs/blob/60a07d852d31f3816e3d8718cb1722e3c892f58d/06-single-hop-udp/README.md#task-06---empty-udp-on-iotlab-m3'}]}, {'name': '07-multi-hop', 'url': 'https://github.com/RIOT-OS/Release-Specs/blob/60a07d852d31f3816e3d8718cb1722e3c892f58d/07-multi-hop/example_test_guide.md', 'subtasks': [{'name': 'Task #01 - ICMPv6 echo on iotlab-m3 with three hops (static route)', 'url': 'https://github.com/RIOT-OS/Release-Specs/blob/60a07d852d31f3816e3d8718cb1722e3c892f58d/07-multi-hop/example_test_guide.md#task-01---icmpv6-echo-on-iotlab-m3-with-three-hops-static-route'}, {'name': 'Task #02 - UDP on iotlab-m3 with three hops (static route)', 'url': 'https://github.com/RIOT-OS/Release-Specs/blob/60a07d852d31f3816e3d8718cb1722e3c892f58d/07-multi-hop/example_test_guide.md#task-02---udp-on-iotlab-m3-with-three-hops-static-route'}, {'name': 'Task #03 - ICMPv6 echo on iotlab-m3 with three hops (RPL route)', 'url': 'https://github.com/RIOT-OS/Release-Specs/blob/60a07d852d31f3816e3d8718cb1722e3c892f58d/07-multi-hop/example_test_guide.md#task-03---icmpv6-echo-on-iotlab-m3-with-three-hops-rpl-route'}, {'name': 'Task #04 - UDP on iotlab-m3 with three hops (RPL route)', 'url': 'https://github.com/RIOT-OS/Release-Specs/blob/60a07d852d31f3816e3d8718cb1722e3c892f58d/07-multi-hop/example_test_guide.md#task-04---udp-on-iotlab-m3-with-three-hops-rpl-route'}, {'name': 'Task #05 (Experimental) - UDP with large payload on iotlab-m3 with three hops (RPL route)', 'url': 'https://github.com/RIOT-OS/Release-Specs/blob/60a07d852d31f3816e3d8718cb1722e3c892f58d/07-multi-hop/example_test_guide.md#task-05-experimental---udp-with-large-payload-on-iotlab-m3-with-three-hops-rpl-route'}]}, {'name': '08-interop', 'url': 'https://github.com/RIOT-OS/Release-Specs/blob/60a07d852d31f3816e3d8718cb1722e3c892f58d/08-interop/README.md', 'subtasks': [{'name': 'Task #01 - ICMPv6 echo between native and Linux', 'url': 'https://github.com/RIOT-OS/Release-Specs/blob/60a07d852d31f3816e3d8718cb1722e3c892f58d/08-interop/README.md#task-01---icmpv6-echo-between-native-and-linux'}, {'name': 'Task #02 - ICMPv6 echo between iotlab-m3 and Linux with 6LowPAN', 'url': 'https://github.com/RIOT-OS/Release-Specs/blob/60a07d852d31f3816e3d8718cb1722e3c892f58d/08-interop/README.md#task-02---icmpv6-echo-between-iotlab-m3-and-linux-with-6lowpan'}, {'name': 'Task #03 - UDP exchange between iotlab-m3 and Contiki', 'url': 'https://github.com/RIOT-OS/Release-Specs/blob/60a07d852d31f3816e3d8718cb1722e3c892f58d/08-interop/README.md#task-03---udp-exchange-between-iotlab-m3-and-contiki'}, {'name': 'Task #04 - ICMPv6 echo between iotlab-m3 and Internet host through Linux with 6LowPAN', 'url': 'https://github.com/RIOT-OS/Release-Specs/blob/60a07d852d31f3816e3d8718cb1722e3c892f58d/08-interop/README.md#task-04---icmpv6-echo-between-iotlab-m3-and-internet-host-through-linux-with-6lowpan'}, {'name': 'Task #05 - ICMPv6 echo between iotlab-m3 and Internet host through RIOT border router', 'url': 'https://github.com/RIOT-OS/Release-Specs/blob/60a07d852d31f3816e3d8718cb1722e3c892f58d/08-interop/README.md#task-05---icmpv6-echo-between-iotlab-m3-and-internet-host-through-riot-border-router'}, {'name': 'Task #06 - UDP between iotlab-m3 and Internet host through RIOT border router', 'url': 'https://github.com/RIOT-OS/Release-Specs/blob/60a07d852d31f3816e3d8718cb1722e3c892f58d/08-interop/README.md#task-06---udp-between-iotlab-m3-and-internet-host-through-riot-border-router'}, {'name': 'Task #07 - UDP between iotlab-m3 and Internet host through RIOT border router (200b payload)', 'url': 'https://github.com/RIOT-OS/Release-Specs/blob/60a07d852d31f3816e3d8718cb1722e3c892f58d/08-interop/README.md#task-07---udp-between-iotlab-m3-and-internet-host-through-riot-border-router-200b-payload'}, {'name': 'Task #08 - UDP between GNRC and lwIP on iotlab-m3', 'url': 'https://github.com/RIOT-OS/Release-Specs/blob/60a07d852d31f3816e3d8718cb1722e3c892f58d/08-interop/README.md#task-08---udp-between-gnrc-and-lwip-on-iotlab-m3'}, {'name': 'Task #09 - deprecated', 'url': 'https://github.com/RIOT-OS/Release-Specs/blob/60a07d852d31f3816e3d8718cb1722e3c892f58d/08-interop/README.md#task-09---deprecated'}, {'name': 'Task #10 - deprecated', 'url': 'https://github.com/RIOT-OS/Release-Specs/blob/60a07d852d31f3816e3d8718cb1722e3c892f58d/08-interop/README.md#task-10---deprecated'}, {'name': 'Task #11 - UDP exchange between iotlab-m3 and Zephyr', 'url': 'https://github.com/RIOT-OS/Release-Specs/blob/60a07d852d31f3816e3d8718cb1722e3c892f58d/08-interop/README.md#task-11---udp-exchange-between-iotlab-m3-and-zephyr'}]}, {'name': '09-coap', 'url': 'https://github.com/RIOT-OS/Release-Specs/blob/60a07d852d31f3816e3d8718cb1722e3c892f58d/09-coap/README.md', 'subtasks': [{'name': 'Task #01 - CORD Endpoint', 'url': 'https://github.com/RIOT-OS/Release-Specs/blob/60a07d852d31f3816e3d8718cb1722e3c892f58d/09-coap/README.md#task-01---cord-endpoint'}, {'name': 'Task #02 - Confirmable retries', 'url': 'https://github.com/RIOT-OS/Release-Specs/blob/60a07d852d31f3816e3d8718cb1722e3c892f58d/09-coap/README.md#task-02---confirmable-retries'}, {'name': 'Task #03 - Block1', 'url': 'https://github.com/RIOT-OS/Release-Specs/blob/60a07d852d31f3816e3d8718cb1722e3c892f58d/09-coap/README.md#task-03---block1'}, {'name': 'Task #04 - Block2', 'url': 'https://github.com/RIOT-OS/Release-Specs/blob/60a07d852d31f3816e3d8718cb1722e3c892f58d/09-coap/README.md#task-04---block2'}, {'name': 'Task #05 - Observe registration and notification', 'url': 'https://github.com/RIOT-OS/Release-Specs/blob/60a07d852d31f3816e3d8718cb1722e3c892f58d/09-coap/README.md#task-05---observe-registration-and-notification'}]}, {'name': '10-icmpv6-error', 'url': 'https://github.com/RIOT-OS/Release-Specs/blob/60a07d852d31f3816e3d8718cb1722e3c892f58d/10-icmpv6-error/README.md', 'subtasks': [{'name': 'Task #01 - Destination unreachable - no route to destination', 'url': 'https://github.com/RIOT-OS/Release-Specs/blob/60a07d852d31f3816e3d8718cb1722e3c892f58d/10-icmpv6-error/README.md#task-01---destination-unreachable---no-route-to-destination'}, {'name': 'Task #02 - Destination unreachable - Beyond scope of source address', 'url': 'https://github.com/RIOT-OS/Release-Specs/blob/60a07d852d31f3816e3d8718cb1722e3c892f58d/10-icmpv6-error/README.md#task-02---destination-unreachable---beyond-scope-of-source-address'}, {'name': 'Task #03 - Destination unreachable - address unreachable (target node address)', 'url': 'https://github.com/RIOT-OS/Release-Specs/blob/60a07d852d31f3816e3d8718cb1722e3c892f58d/10-icmpv6-error/README.md#task-03---destination-unreachable---address-unreachable-target-node-address'}, {'name': 'Task #04 - Destination unreachable - address unreachable (neighbor cache miss)', 'url': 'https://github.com/RIOT-OS/Release-Specs/blob/60a07d852d31f3816e3d8718cb1722e3c892f58d/10-icmpv6-error/README.md#task-04---destination-unreachable---address-unreachable-neighbor-cache-miss'}, {'name': 'Task #05 - Destination unreachable - port unreachable', 'url': 'https://github.com/RIOT-OS/Release-Specs/blob/60a07d852d31f3816e3d8718cb1722e3c892f58d/10-icmpv6-error/README.md#task-05---destination-unreachable---port-unreachable'}, {'name': 'Task #06 - Destination unreachable - port unreachable (large payload)', 'url': 'https://github.com/RIOT-OS/Release-Specs/blob/60a07d852d31f3816e3d8718cb1722e3c892f58d/10-icmpv6-error/README.md#task-06---destination-unreachable---port-unreachable-large-payload'}, {'name': 'Task #07 - Packet too big', 'url': 'https://github.com/RIOT-OS/Release-Specs/blob/60a07d852d31f3816e3d8718cb1722e3c892f58d/10-icmpv6-error/README.md#task-07---packet-too-big'}, {'name': 'Task #08 - Time exceeded - hop limit exceeded in transit', 'url': 'https://github.com/RIOT-OS/Release-Specs/blob/60a07d852d31f3816e3d8718cb1722e3c892f58d/10-icmpv6-error/README.md#task-08---time-exceeded---hop-limit-exceeded-in-transit'}, {'name': 'Task #09 - Parameter problem - erroneous header field encountered', 'url': 'https://github.com/RIOT-OS/Release-Specs/blob/60a07d852d31f3816e3d8718cb1722e3c892f58d/10-icmpv6-error/README.md#task-09---parameter-problem---erroneous-header-field-encountered'}, {'name': 'Task #10 - IPv6-in-IPv6 encapsulation', 'url': 'https://github.com/RIOT-OS/Release-Specs/blob/60a07d852d31f3816e3d8718cb1722e3c892f58d/10-icmpv6-error/README.md#task-10---ipv6-in-ipv6-encapsulation'}]}, {'name': '11-lorawan', 'url': 'https://github.com/RIOT-OS/Release-Specs/blob/60a07d852d31f3816e3d8718cb1722e3c892f58d/11-lorawan/README.md', 'subtasks': [{'name': 'Task #01 - LoRaWAN example', 'url': 'https://github.com/RIOT-OS/Release-Specs/blob/60a07d852d31f3816e3d8718cb1722e3c892f58d/11-lorawan/README.md#task-01---lorawan-example'}, {'name': 'Task #02 - OTAA join procedure', 'url': 'https://github.com/RIOT-OS/Release-Specs/blob/60a07d852d31f3816e3d8718cb1722e3c892f58d/11-lorawan/README.md#task-02---otaa-join-procedure'}, {'name': 'Task #03 - ABP join procedure', 'url': 'https://github.com/RIOT-OS/Release-Specs/blob/60a07d852d31f3816e3d8718cb1722e3c892f58d/11-lorawan/README.md#task-03---abp-join-procedure'}, {'name': 'Task #04 - LoRaWAN device parameters persistence', 'url': 'https://github.com/RIOT-OS/Release-Specs/blob/60a07d852d31f3816e3d8718cb1722e3c892f58d/11-lorawan/README.md#task-04---lorawan-device-parameters-persistence'}]}, {'name': '99-compile-and-test-one-board', 'url': 'https://github.com/RIOT-OS/Release-Specs/blob/60a07d852d31f3816e3d8718cb1722e3c892f58d/99-compile-and-test-one-board/README.md', 'subtasks': [{'name': 'Task #01 - Run tests on different hardwares', 'url': 'https://github.com/RIOT-OS/Release-Specs/blob/60a07d852d31f3816e3d8718cb1722e3c892f58d/99-compile-and-test-one-board/README.md#task-01---run-tests-on-different-hardwares'}]}]
```

**Comment by fjmolinas** [comment]
If there was no match it would have been like `[{'name': '01-ci'}, {'name': '02-tests'}, {'name': '03-single-hop-ipv6-icmp'}, {'name': '04-single-hop-6lowpan-icmp'}, {'name': '05-single-hop-route'}, {'name': '06-single-hop-udp'}, {'name': '07-multi-hop'}, {'name': '08-interop'}, {'name': '09-coap'}, {'name': '10-icmpv6-error'}, {'name': '11-lorawan'}, {'name': '99-compile-and-test-one-board'}]
`

**Pull request merged**
