### PR TITLE
09-coap/task02&05: shutdown server properly

### PR DESCRIPTION
**Pull request by miri64**
Apparently, just killing the aiocoap server is not such a good idea ;-). With this fix all CoAP tests succeed.

#### Testing procedures
Currently when run completely spec09 is failing on the last task

```sh
sudo RIOTBASE=$(readlink -f ../RIOT) tox -e test -- -k "spec09" --non-RC
```

the reason is because both task02 and task09 start a CoAP server. This can be shown by just running those tasks (for task02 only the version that starts the server)

```sh
sudo RIOTBASE=$(readlink -f ../RIOT) tox -e test -- -k "spec09 and ((task02 and True) or task05)" --non-RC
```

On current master this is broken, with this PR all tasks will succeed again.

### CODE REVIEW

**Comment by miri64** [comment]
Rebased to current master.

**Comment by fjmolinas** [comment]
Any idea why this did not happen locally?

**Comment by miri64** [comment]
It does happen locally, at least on my machine (see testing procedure). I'm not sure if in #168 the PR was not tested after my [task02 rework](https://github.com/RIOT-OS/Release-Specs/pull/168#issuecomment-665165252) or if it is just not reproducable on your machine.

**Comment by fjmolinas** [comment]
> It does happen locally, at least on my machine (see testing procedure). I'm not sure if in #168 the PR was not tested after my task02 rework or if it is just not reproducable on your machine.

I'll re run and see if I can reproduce, but the fix makes sense on itself.

**Comment by fjmolinas** [comment]
Strange I'm doing the following and the tests passes:

```
 sudo "PYTHONPATH=$PYTHONPATH" "PATH=$PATH" -E /home/francisco/.virtualenvs/release/bin/pytest 09-coap/ --non-RC  -k "test_task02 or test_task09"
```

**Comment by fjmolinas** [comment]
I also get the failure:

```
>
----------------------------------------------------------- Captured log call -----------------------------------------------------------
WARNING  coap-server:messagemanager.py:197 Received Type.ACK from <UDP6EndpointAddress [fd00:bbbb::2] with local address>, but could not match it to a running exchange.
------------------------------ generated xml file: /home/francisco/workspace/Release-Specs/test-report.xml ------------------------------
========================================= 1 failed, 2 passed, 3 deselected in 120.70s (0:02:00) =========================================
```

And this fixes it:

```
→ sudo "PYTHONPATH=$PYTHONPATH" "PATH=$PATH" -E /home/francisco/.virtualenvs/release/bin/pytest 09-coap/ --non-RC  -k "test_task02 or test_task05"
========================================================== test session starts ==========================================================
platform linux -- Python 3.6.9, pytest-5.4.3, py-1.9.0, pluggy-0.13.1 -- /home/francisco/.virtualenvs/release/bin/python3
cachedir: .pytest_cache
rootdir: /home/francisco/workspace/Release-Specs, inifile: setup.cfg
plugins: cov-2.10.0
collected 6 items / 3 deselected / 3 selected

09-coap/test_spec09.py::test_task02[nodes0-True-1] PASSED                                                                         [ 33%]
09-coap/test_spec09.py::test_task02[nodes1-False-0] PASSED                                                                        [ 66%]
09-coap/test_spec09.py::test_task05[nodes0] PASSED                                                                                [100%]

------------------------------ generated xml file: /home/francisco/workspace/Release-Specs/test-report.xml ------------------------------
============================================== 3 passed, 3 deselected in 109.53s (0:01:49) ==============================================
```

**Comment by miri64** [comment]
Yes, this was exactly the warning I also saw in the logs :-)

**Pull request merged**
